# Data Structure - 2
-  numpy 

## Numpy 
-  similar to list, but items to be one type (so less memory required to store and manipulate) more functions available helps in matrix computations

In [1]:
#%% #numpy - array - same data type - numerical python
list1 = [1,2,3,5]
list1

[1, 2, 3, 5]

In [2]:
import numpy
print(numpy.array([10,20])) #list to numpy array
print(numpy.array([list1])) #list inside a list

[10 20]
[[1 2 3 5]]


In [3]:
import numpy as np #np is alias
print(np.__version__)

1.24.3


In [4]:
np.arange(1,100,10)  #start, stop, setp

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [5]:
#help(np.arange)

In [6]:
np1 = np.arange(1,10)
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x=np.arange(start=1,stop=1000000,step=2)  #very large number series
len(x)

500000

In [8]:
print(x[1:100])  # print from 1st position to 100th position
print()
print(x[1:50:10])  # print at interval of 10 starting 1st position to 50th position

[  3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35  37
  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73
  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107 109
 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143 145
 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179 181
 183 185 187 189 191 193 195 197 199]

[ 3 23 43 63 83]


In [9]:
print(np.mean(np.arange(1,10000000)))
#mean of np array of numbers from 1 to 10^7

5000000.0


In [10]:
print(type(np1))
print(dir(np1), sep ='\t')

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [11]:
#help(np)
#https://numpy.org/doc/stable/user/index.html

## Numpy display options
-  https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html
-  numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)[source]
-  np.set_printoptions(edgeitems=30, linewidth=100000,   formatter=dict(float=lambda x: "%.3g" % x))
-  np.set_printoptions(edgeitems=3)
-  np.core.arrayprint._line_width = 80
-  np.set_printoptions(edgeitems=10,linewidth=180)

## Array Creation

In [12]:
np.array(([1,2,3,4,10]))  # from list

array([ 1,  2,  3,  4, 10])

In [13]:
np.zeros((3,4))  # array of 0s; 3ros x 4cols

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,2))  # array of 1s; 2rows x 2cols

array([[1., 1.],
       [1., 1.]])

In [15]:
np.arange(0,10)  #range of values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.random.rand(3, 4)  # array of random nos betw 0 and 1 : shape of 3 rows x 4 cols

array([[0.95254466, 0.30727016, 0.51521714, 0.79993781],
       [0.9142572 , 0.00243109, 0.50129545, 0.42262824],
       [0.52163286, 0.81370929, 0.45332374, 0.44488983]])

## Array Attributes

In [17]:
np2 = np.array([ 90, 50, 60, 70 ])
print(np2)
print('Sorted NP array ', np.sort(np2))

[90 50 60 70]
Sorted NP array  [50 60 70 90]


In [18]:
np3 = np.array([[1,4],[3,1],[5,6],[10,50]])
np3
#multi dim np array like matrix

array([[ 1,  4],
       [ 3,  1],
       [ 5,  6],
       [10, 50]])

In [19]:
print(np3.shape)   #rows, columns
print(np3.shape[0]) #rows
print(np3.shape[1]) #cols
x= np3.shape[0] * np3.shape[1]
print('No of elements ', x)
print(np3.dtype)  # datatype

(4, 2)
4
2
No of elements  8
int32


In [20]:
## slicing\
np4 = np.array(([1,2,3,4,10])) 
np4

array([ 1,  2,  3,  4, 10])

In [21]:
print(np4[0])  # first element
print(np4[-1])  #last element
print(np4[1:3])  #slice from 2nd to 3rd

1
10
[2 3]


In [22]:
print(x%2 == 0)   #divisible by 2 : Even no of elements
print(x%3 == 0)   #divisible by 3
print(len(np3))   #no of rows

True
False
4


In [23]:
np3

array([[ 1,  4],
       [ 3,  1],
       [ 5,  6],
       [10, 50]])

In [24]:
# change the shape of np array - vertical stack
np3.reshape((-1,1))  #1 column from 2 column
#np.reshape((-1, noCols))   # from any number of columns change to 1 columns

array([[ 1],
       [ 4],
       [ 3],
       [ 1],
       [ 5],
       [ 6],
       [10],
       [50]])

In [25]:
np3.reshape((-1))   # no columns

array([ 1,  4,  3,  1,  5,  6, 10, 50])

In [26]:
np3.reshape((-1,2))

array([[ 1,  4],
       [ 3,  1],
       [ 5,  6],
       [10, 50]])

In [27]:
#np3.reshape((-1,3))  #error
#cannot be converted to 3 columns as there are 8 elements and 8 is not divisible by 3

## Stacking

In [28]:
# Vertical Stack
np.vstack([np3, np3])

array([[ 1,  4],
       [ 3,  1],
       [ 5,  6],
       [10, 50],
       [ 1,  4],
       [ 3,  1],
       [ 5,  6],
       [10, 50]])

In [29]:
np.hstack([np3, np3])

array([[ 1,  4,  1,  4],
       [ 3,  1,  3,  1],
       [ 5,  6,  5,  6],
       [10, 50, 10, 50]])

In [30]:
## Aritmetic Operations

In [31]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1, arr2)

[1 2 3] [4 5 6]


In [32]:
arr1 + arr2

array([5, 7, 9])

In [33]:
arr1 - arr2

array([-3, -3, -3])

In [34]:
arr1 * arr2

array([ 4, 10, 18])

In [35]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

## Statistics

In [36]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [37]:
print(np.mean(arr))  #mean
print(np.median(arr))  #median
print(np.std(arr))  #sd
print(np.max(arr))  #max
print(np.min(arr))  #min
print(np.var(arr))  #variance

3.0
3.0
1.4142135623730951
5
1
2.0


## Blank
-  

## Links
-  

## Next 
-  Pandas