# Linear Regression in Python
-  Simple Case
-  https://realpython.com/linear-regression-in-python/

In [1]:
#import libraries

In [3]:
import numpy as np
import pandas as pd
from pydataset import data

In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])
print(x, '\n', y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]] 
 [ 5 20 14 32 22 38]


In [6]:
model = LinearRegression()

In [5]:
model.fit(x, y)

LinearRegression()

In [8]:
model = LinearRegression().fit(x, y)

In [9]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [10]:
y_pred = model.predict(x).round(2)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33 13.73 19.13 24.53 29.93 35.33]


In [11]:
y_pred = model.intercept_ + model.coef_ * x

In [12]:
x_new = np.arange(5).reshape((-1, 1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [13]:
y_new = model.predict(x_new)
print(y_new.round(2))

[5.63 6.17 6.71 7.25 7.79]


### End here